DATA_FOLDER = "data"
PASSERELLE_FOLDER = "data/passerelle"

DRIVE_MAIN_FOLDER_ID = "1wXIqggriTHD9NIx8U89XmtlbZqNWniGD"
DRIVE_PASSERELLE_FOLDER_ID = "19_ZU-FsAiNKxCfTw_WKzhTcuPDsGoVhL"
DRIVE_GPS_FOLDER_ID = "1v4Iit4JlEDNACp2QWQVrP89j66zBqMFH"

PERMISSIONS_FILENAME = "Classeurs permissions streamlit.xlsx"
EDF_JOUEUSES_FILENAME = "EDF_Joueuses.xlsx"
PASSERELLE_FILENAME = "Liste Joueuses Passerelles.xlsx"
REFERENTIEL_FILENAME = "Noms Prénoms Paris FC.xlsx"

POST_COLS = ["ATT","DCD","DCG","DD","DG","GB","MCD","MCG","MD","MDef","MG"]
BAD_TOKENS = {"CORNER","COUP-FRANC","COUP FRANC","PENALTY","CARTON","CARTONS"}
GPS_GF1_PREFIX = "GF1"
